<!--
 * @Description:try...catch + 回调函数
 * @Author: xiao.zhang
 * @Date: 2020-10-23 15:42:08
 * @LastEditors: xiao.zhang
 * @LastEditTime: 2020-10-26 16:37:08
-->

#### 1,背景

###### 维基百科上面的一段话:

- 异步通信（英语：Asynchronous conferencing）是科学领域中正式使用的术语，特指以计算机为介质，沟通，协作和学习，在互动贡献者中有一定延迟的技术。
- 与之相对的是同步通信，同步会议指各种“聊天”系统，在该系统中，用户“实时”同步通信

在将来执行的程序可以看做是异步的。比如我们注册了一个 setTimeout，但并没有马上执行里面的回调函数，setTimeout 的这个表现就是异步的。或者我们发送一个请求，但是并没有立刻得到数据，也是异步的表现

###### 例子：

```
// 依次打印出first、third、second
console.log('first');
setTimeout(() => {
    console.log('second');
}, 1000)
console.log('third');
```

**如果你还不能理解，那么假设我们有个烧水壶。我们烧水的时候，如果一直在旁边等着，直到水烧开去接水，这就是同步。如果我们在烧水的时候离开去做自己的事情，等水烧开后会提醒你水烧开了，你再去接水，这就是异步**

假如我们想在水烧开后去做某件事情，这个时候该如何操作？然后就出现回调函数+Promise

#### 2,回调函数

- 接触最早的异步处理就是回调函数，我们可以规定在等待某个异步操作返回结果后，就去执行这个回调函数
- 例子：

```
const sleep = (time, callback) => {
    setTimeout(() => {
        callback();
    }, time)
}
```

##### 回调函数的弊端

- 1,回调地狱

我们有一个例子，假设我们控制一个红绿灯切换的动画（红绿灯时间都是 60s）。由于每次都要依赖前一次的灯到时间，所以只能在对方的回调函数里面执行。这样就造成了一层层回调函数嵌套。

```
 green(60, function() {
        red(60, function() {
            green(60, function() {
                red(60, function() {
                    green(60, function() {
                        // ...
                    })
                })
            })
        })
    })
```

这样的代码风格一般被我们称为回调地狱。从直观上来看，函数一层层嵌套，让可读性和可维护性变得非常差。

- 2,错误跟踪

###### 由于异步的存在，导致 try...catch 无法捕获到异步调用中的异常，导致调试变得很难。

```
const time = (callback) => {
  setTimeout(() => {
    try {
        console.log(aaaa) // aaaa未定义
        callback()
    } catch (err) {
        throw err // 可以拿到报错信息
    }
  }, 1000)
}
const cb = () => {
  console.log('success')
}
// try...catch无法捕获到time中的报错
try {
  time(cb)
} catch (err) {
  console.log('err', err)// 无法拿到报错信息
}
```

为了解决上面的问题，有 2 种方式：将成功和失败的回调分开
例子：

```
const time = (successCallback, failCallback) => {
  setTimeout(() => {
    try {
        console.log(aaaa) // aaaa未定义
        successCallback()
    } catch (err) {
      failCallback(err)
    }
  }, 1000)
}

const success = () => {
  console.log('success')
}

const fail = () => {
  console.log('success')
}

time(success,fail)
```

第二种解决方案暂时没看懂

- 3，失去控制权
- 4，并行问题

假设我们有一种场景，需要等待三个接口都请求成功后，我们再去执行某个操作，这样我们该怎么知道三个接口什么时候全部请求成功呢？
我们是对三个接口分别设置三个不同的变量，执行成功后修改这个变量的值，在每个接口中都判断一下？

```
let isASuccess = false,
    isBSuccess = false,
    isCSuccess = false;
function ajaxA (callback) {
    // 请求成功后
    isASuccess = true;
    if (isBSuccess && isCSuccess) {
        callback();
    }
}
function ajaxB (callback) {
    // 请求成功后
    isBSuccess = true;
    if (isASuccess && isCSuccess) {
        callback();
    }
}
function ajaxC (callback) {
    // 请求成功后
    isCSuccess = true;
    if (isASuccess && isBSuccess) {
        callback();
    }
}
```

##### 3，try...catch 的用途

- 在程序逻辑中，需要在易出现问题的逻辑代码片段上，加持 try-catch 方法。
  这样做可以抛出错误，但是不会影响整个程序运转

```
try {
	// 你的逻辑代码片段
} catch (e) {
	// 错误处理代码片段
}
```

- try 中有错误的代码，在 catch 中可以捕获到

- try catch 不能做真假判断，只能做真假判断，window.a.b === 2 结果是否为 true 或 false,对 try...catch 没有任何影响。但如果 b 不存在，则会抛出错误

##### try...catch 的适用场景

- 永远应该放在你的控制范围之内，而不应该防范未知的错误。也就是说你很清楚知道这里是有可能”出错“的，而且你很清楚知道什么前提下会出错，你就是要故意利用报错信息来区分错误，后续的程序会解决所有的出错，让程序继续执行。
  如果让用户先发现你根本没预料到的错误，而不是你先发现错误，你是失职的。
- 浏览器原罪的场合：也就是兼容性场合，因为浏览器兼容性不是程序员能改正的，所以只能 try catch：由于不同浏览器的报错提示是不一样的，根据捕获的浏览器的报错提示判断用户的浏览器，然后做出对应的措施，这时候使用 try catch 是巧妙的办法，如果用 if 就比较笨拙，因为 if 通常只能反馈真或假，不能直接反馈浏览器的报错内容。（你觉得会出现浏览器兼容的地方加上）
